export const MORTGAGE_UPDATE_SCENARIO = 'MORTGAGE_UPDATE_SCENARIO';
export const MORTGAGE_UPDATE_ACTIVE_SCENARIO = 'MORTGAGE_UPDATE_ACTIVE_SCENARIO';
export const MORTGAGE_UPDATE_ASKING_PRICE = 'MORTGAGE_UPDATE_ASKING_PRICE';

export const LOCALIZATION_SET_LANG = 'LOCALIZATION_SET_LANG';
