export default {
  ASKING_PRICE: 'asking price',
  DOWN_PAYMENT: 'down payment',
  CLOSE: 'close',
  TOTAL_MORTGAGE: 'mortgage required',
  AMORTIZATION_PERIOD: 'amortization period',
  MORTGAGE_RATE: 'mortgage rate',
  TOTAL_MORTGAGE_PAYMENT: 'total mortgage payment',
  TOTAL_INTEREST: 'total interest',
  YEARS: 'years',
  MONTHLY_PAYMENT: 'monthly payment',
  CANCEL: 'Cancel',
  OK: 'Ok',
  ARE_YOU_SURE: 'Are you sure?',
  CONFIRM_RESET: `All the changes you've made will be deleted.`,
  SCENARIO_TITLE: 'Name of the Scenario',
  PRINCIPAL: 'Principal',
  INTERESTS: 'Interests',
  CANNOT_DISPLAY_CHART: 'We cannot display the chart just yet',
  MISSING_CHART_DATA: 'Some values are missing to be able to recalculate the repayment schedule for',
  MORTGAGE_CALCULATOR: 'Mortgage Calculator',
  COMPOUND_INTEREST_CALCULATOR: 'Compound Interest Calculator',
  SETTINGS: 'Settings',
  MONTHLY_CONTRIBUTION: 'Monthly Contribution',
  TOTAL_CONTRIBUTION: 'Total contributions',
  TOTAL_COMPOUND: 'Total value at term',
  DURATION: 'Duration',
  INTEREST_RATE: 'Interest rate',
  MISSING_COMPOUND_CHART_DATA: 'Some values are missing to be able to recalculate the compound interests chart',
  COMPOUND_INTERESTS: 'Compound Interests'
};
