export default {
  ASKING_PRICE: 'prix de départ',
  DOWN_PAYMENT: 'apport',
  CLOSE: 'fermer',
  TOTAL_MORTGAGE: 'emprunt',
  AMORTIZATION_PERIOD: 'durée du prêt',
  MORTGAGE_RATE: `taux d'emprunt`,
  TOTAL_MORTGAGE_PAYMENT: 'montant total du prêt',
  TOTAL_INTEREST: 'total des intérêts',
  YEARS: 'ans',
  MONTHLY_PAYMENT: 'mensualité',
  CANCEL: 'Annuler',
  OK: 'Ok',
  ARE_YOU_SURE: 'Êtes-vous sûr?',
  CONFIRM_RESET: 'Tous vos changements vont être effacés.',
  SCENARIO_TITLE: 'Nom du Scenario',
  PRINCIPAL: 'Principal',
  INTERESTS: 'Interêts',
  CANNOT_DISPLAY_CHART: 'Nous ne pouvons pas encore générer de graphique',
  MISSING_CHART_DATA: `Certaines valeurs sont encore manquantes pour calculer l'échéancier du`,
  MORTGAGE_CALCULATOR: `Calculateur d'emprunt`,
  COMPOUND_INTEREST_CALCULATOR: `Calculateur d'intérêts`,
  SETTINGS: 'Préférences'
};
